### ISSUE TITLE
AttributeError: 'UnifiVoucherButton' object has no attribute 'self'

### ISSUE THREAD

**Issue by arnkit** [ufozone/ha-unifi-voucher#22]
Hey,
First of all: Thanks for the good work. Its great to have the integration in HA.
Unfortunatly after the last update of HA, I experience the following error:

AttributeError: 'UnifiVoucherButton' object has no attribute 'self'

`2024-02-08 09:32:00.756 DEBUG (MainThread) [custom_components.unifi_voucher] Finished fetching unifi_voucher data in 0.036 seconds (success: True)
2024-02-08 09:32:00.762 ERROR (MainThread) [homeassistant.components.button] Error while setting up unifi_voucher platform for button
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 344, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/unifi_voucher/button.py", line 71, in async_setup_entry
    UnifiVoucherButton(
  File "/config/custom_components/unifi_voucher/button.py", line 90, in __init__
    super().__init__(
  File "/config/custom_components/unifi_voucher/entity.py", line 48, in __init__
    configuration_url=self.self.coordinator.get_configuration_url(),
                      ^^^^^^^^^
AttributeError: 'UnifiVoucherButton' object has no attribute 'self'
2024-02-08 09:32:00.773 ERROR (MainThread) [homeassistant.components.image] Error while setting up unifi_voucher platform for image
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 344, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/unifi_voucher/image.py", line 50, in async_setup_entry
    UnifiVoucherImage(
  File "/config/custom_components/unifi_voucher/image.py", line 75, in __init__
    super().__init__(
  File "/config/custom_components/unifi_voucher/entity.py", line 48, in __init__
    configuration_url=self.self.coordinator.get_configuration_url(),
                      ^^^^^^^^^
AttributeError: 'UnifiVoucherImage' object has no attribute 'self'
2024-02-08 09:32:00.783 ERROR (MainThread) [homeassistant.components.number] Error while setting up unifi_voucher platform for number
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 344, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/unifi_voucher/number.py", line 56, in async_setup_entry
    UnifiVoucherNumber(
  File "/config/custom_components/unifi_voucher/number.py", line 77, in __init__
    super().__init__(
  File "/config/custom_components/unifi_voucher/entity.py", line 48, in __init__
    configuration_url=self.self.coordinator.get_configuration_url(),
                      ^^^^^^^^^
AttributeError: 'UnifiVoucherNumber' object has no attribute 'self'
2024-02-08 09:32:00.791 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up unifi_voucher platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 344, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/unifi_voucher/sensor.py", line 46, in async_setup_entry
    UnifiVoucherSensor(
  File "/config/custom_components/unifi_voucher/sensor.py", line 65, in __init__
    super().__init__(
  File "/config/custom_components/unifi_voucher/entity.py", line 48, in __init__
    configuration_url=self.self.coordinator.get_configuration_url(),
                      ^^^^^^^^^
AttributeError: 'UnifiVoucherSensor' object has no attribute 'self'`

Any Idea?

---

I'm running a UDM Pro with UniFi OS v3.2.9
and HA Core 2024.2.0
Tried to delete and reintegrate the Hub, but still the same issue.

**Comment by CoolhappyDE** [comment]
hey, i have the same issue after i updated to 24.2. 

the version of the Networkcontroller is: Network 8.0.28
And UniFi OS is: 3.2.9

**Comment by ufozone** [comment]
I'll have a look at it and fix it by tonight.

**Comment by ufozone** [comment]
A new release has been published:
[v1.1.3](https://github.com/ufozone/ha-unifi-voucher/releases/tag/v1.1.3)
